server {
        listen 80;
        server_name colegiados.cppe-puno.org.pe;

        location / {
                return 301 https://$host$request_uri;
        }
}

server {
        listen 443 ssl;
        server_name colegiados.cppe-puno.org.pe;

        client_max_body_size 20M;

        ssl_certificate /etc/letsencrypt/live/colegiados.cppe-puno.org.pe/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/colegiados.cppe-puno.org.pe/privkey.pem;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;

        location /static/ {
                alias /var/www/cppe/staticfiles/;
                autoindex off;
                expires 3M;
                access_log off;
        }

        location /media/ {
                alias /var/www/cppe/media/;
                autoindex off;
                expires 4w;
        }

        location /favicon.ico {
                alias /var/www/cppe/staticfiles/favicon.ico;
                expires 6M;
                access_log off;
        }

        location / {
                include uwsgi_params;
                uwsgi_pass unix:/run/uwsgi/cppe.sock;

                uwsgi_param Host $host;
                uwsgi_param X-Real-IP $remote_addr;
                uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
                uwsgi_param X-Forwarded-Proto $scheme;
        }

        access_log /var/log/nginx/cppe_access.log;
        error_log /var/log/nginx/cppe_error.log warn;

}