[uwsgi]
chdir = /home/rene/production
module = mysite.wsgi:application
home = /home/rene/entorno

# http = 0.0.0.0:8000
socket = /run/uwsgi/courses.sock
chmod-socket = 660
chown-socket = rene:www-data


master = true
processes = 4
threads = 2

listen = 1024
thunder-lock = true

vacuum = true

logto = /var/log/uwsgi/courses.log
log-maxsize = 10000000
disable-login = false
