# Generated by Django 6.1.1 on 2026-09-05 22:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('registration_code', models.CharField(max_length=20, unique=True, verbose_name='Código de Colegiatura')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='Mes')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=6, verbose_name='Monto')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° Comprobante')),
                ('comments', models.TextField(blank=True, verbose_name='Comentarios')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Aporte',
                'verbose_name_plural': 'Aportes',
                'db_table': 'contributions',
                'ordering': ['-year', '-month'],
                'unique_together': {('teacher', 'month', 'year')},
            },
        ),
    ]
