# Generated by Django 6.1.1 on 2026-09-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI consultado')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('found', models.BooleanField(default=False, verbose_name='¿Encontrado?')),
            ],
            options={
                'verbose_name': 'Consulta pública',
                'verbose_name_plural': 'Consultas públicas',
                'db_table': 'public_query_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
